import { ScreenNamesType } from './types';

export const SCREEN_NAMES: ScreenNamesType = {
    HOME_SCREEN: 'HOME_SCREEN',
    SETTINGS_SCREEN: 'SETTINGS_SCREEN',
    NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
    ANOTHER_SCREEN: 'ANOTHER_SCREEN',
    TYPOGRAPHY_EXAMPLE_SCREEN: 'TYPOGRAPHY_EXAMPLE_SCREEN',
};

export const STACK_NAMES = {
    TAB_STACK: 'TAB_STACK',
    HOME_STACK: 'HOME_STACK',
};
